<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 RoadStraight.glb --transform --shadows --root=roads/
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('roads/RoadStraight-transformed.glb', { useDraco: true })

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group position={[0, 0, 0.75]}>
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Mesh_road_straight.geometry}
        material={gltf.materials.pavement}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Mesh_road_straight_1.geometry}
        material={gltf.materials.asphalt}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Mesh_road_straight_2.geometry}
        material={gltf.materials.asphaltEdge}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Mesh_road_straight_3.geometry}
        material={gltf.materials.line}
      />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
