<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 Pallet.glb --transform --shadows
-->

<script>
	import { Group, MeshStandardMaterial } from 'three';
	import { T, forwardEventHandlers } from '@threlte/core';
	import { useGltf } from '@threlte/extras';
	import { AutoColliders, Collider, RigidBody } from '@threlte/rapier';

	export const ref = new Group();

	const gltf = useGltf('/Pallet-transformed.glb', { useDraco: true });

	const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group position={[0, -0.02, -0.01]}>
			<Collider args={[0.05, 0.06, 0.065]} shape="cuboid" />
		</T.Group>
		<T.Group position={[0.325, -0.02, -0.01]}>
			<Collider args={[0.05, 0.06, 0.065]} shape="cuboid" />
		</T.Group>
		<T.Group position={[-0.325, -0.02, -0.01]}>
			<Collider args={[0.05, 0.06, 0.065]} shape="cuboid" />
		</T.Group>

		<T.Group position={[0, -0.02, -0.51]}>
			<Collider args={[0.05, 0.06, 0.065]} shape="cuboid" />
		</T.Group>
		<T.Group position={[0.325, -0.02, -0.51]}>
			<Collider args={[0.05, 0.06, 0.065]} shape="cuboid" />
		</T.Group>
		<T.Group position={[-0.325, -0.02, -0.51]}>
			<Collider args={[0.05, 0.06, 0.065]} shape="cuboid" />
		</T.Group>

		<T.Group position={[0, -0.02, 0.52]}>
			<Collider args={[0.05, 0.06, 0.065]} shape="cuboid" />
		</T.Group>
		<T.Group position={[0.325, -0.02, 0.52]}>
			<Collider args={[0.05, 0.06, 0.065]} shape="cuboid" />
		</T.Group>
		<T.Group position={[-0.325, -0.02, 0.52]}>
			<Collider args={[0.05, 0.06, 0.065]} shape="cuboid" />
		</T.Group>

		<T.Group position={[0, -0.07, -0.51]}>
			<Collider args={[0.37, 0.01, 0.065]} shape="cuboid" />
		</T.Group>
		<T.Group position={[0, -0.07, 0.52]}>
			<Collider args={[0.37, 0.01, 0.065]} shape="cuboid" />
		</T.Group>
		<T.Group position={[0, -0.07, -0.01]}>
			<Collider args={[0.37, 0.01, 0.065]} shape="cuboid" />
		</T.Group>

		<!-- Top Collider of Pallet -->
		<T.Group position={[0, 0.04, 0]}>
			<Collider args={[0.37, 0.02, 0.575]} shape="cuboid" />
		</T.Group>

		<T.Mesh
			castShadow
			geometry={gltf.nodes.palletsobj.geometry}
			rotation={[Math.PI / 2, 0, 0]}
			scale={0.2}
		>
			<T.MeshStandardMaterial color="#eecc88" />
		</T.Mesh>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
