<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 C:\Users\conner\Downloads\kenney_space-kit\Models\GLTF format\craft_cargoA.glb --transform
-->

<script lang="ts">
	import { Group, LineBasicMaterial, Mesh } from 'three';
	import { T, forwardEventHandlers } from '@threlte/core';
	import { Edges, Float, useGltf } from '@threlte/extras';
	import { AutoColliders, RigidBody } from '@threlte/rapier';
	import { derived } from 'svelte/store';

	export const ref = new Group();
	export let meshes: Mesh[] = [];

	const gltf = useGltf('/craft_cargoA-transformed.glb', { useDraco: true });

	const component = forwardEventHandlers();

	// const edgesMaterial = new LineBasicMaterial({
	// 	linewidth: 100,
	// 	color: 0x000000
	// });
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<RigidBody>
			<AutoColliders shape="cuboid">
				<Float
					speed={5}
					floatIntensity={0.25}
					rotationIntensity={0.25}
					rotationSpeed={[5, 6, 7]}
					floatingRange={[
						[-1, 1],
						[0, 1],
						[-1, 1]
					]}
				>
					<T.Group>
						<T.Mesh
							bind:ref={meshes[1]}
							castShadow
							geometry={gltf.nodes.Mesh_craft_cargoA.geometry}
							material={gltf.materials.metalDark}
						>
							<!-- <Edges>
								<T.LineBasicMaterial color="black" linewidth={5} />
							</Edges> -->
						</T.Mesh>
						<T.Mesh
							bind:ref={meshes[2]}
							castShadow
							geometry={gltf.nodes.Mesh_craft_cargoA_1.geometry}
							material={gltf.materials.dark}
						>
							<!-- <Edges>
								<T.LineBasicMaterial color="black" linewidth={5} />
							</Edges> -->
						</T.Mesh>
						<T.Mesh
							bind:ref={meshes[3]}
							castShadow
							geometry={gltf.nodes.Mesh_craft_cargoA_2.geometry}
							material={gltf.materials.metalRed}
						>
							<!-- <Edges>
								<T.LineBasicMaterial color="black" linewidth={5} />
							</Edges> -->
						</T.Mesh>
						<T.Mesh
							bind:ref={meshes[4]}
							castShadow
							geometry={gltf.nodes.Mesh_craft_cargoA_3.geometry}
							material={gltf.materials.metal}
						>
							<!-- <Edges>
								<T.LineBasicMaterial color="black" linewidth={5} />
							</Edges> -->
						</T.Mesh>
					</T.Group>
				</Float>
			</AutoColliders>
		</RigidBody>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
