<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 BoxSmall.glb --transform --shadows --root=factory/
-->

<script>
	import { Group } from 'three';
	import { T, forwardEventHandlers } from '@threlte/core';
	import { useGltf } from '@threlte/extras';
	import { AutoColliders } from '@threlte/rapier';

	export const ref = new Group();

	const gltf = useGltf('factory/BoxSmall-transformed.glb', { useDraco: true });

	const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<AutoColliders mass={1} shape="cuboid">
			<!-- receiveShadow -->
			<T.Mesh
				castShadow
				geometry={gltf.nodes['Mesh_box-small'].geometry}
				material={gltf.materials.cardboard}
			/>
			<!-- receiveShadow -->
			<T.Mesh
				castShadow
				geometry={gltf.nodes['Mesh_box-small_1'].geometry}
				material={gltf.materials.tape}
			/>
		</AutoColliders>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
