<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 ConveyorBarsStripeHigh.glb --transform --shadows --root=factory/
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('factory/ConveyorBarsStripeHigh-transformed.glb', { useDraco: true })

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group position={[0, 0.1, 0]}>
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Mesh_Group_28.geometry}
        material={gltf.materials['grey-dark']}
      />
      <T.Mesh castShadow receiveShadow geometry={gltf.nodes.Mesh_Group_28_1.geometry} material={gltf.materials.grey} />
      <T.Mesh castShadow receiveShadow geometry={gltf.nodes.Mesh_Group_28_2.geometry} material={gltf.materials.dark} />
    </T.Group>
    <T.Mesh castShadow receiveShadow geometry={gltf.nodes.Mesh_Group_36.geometry} material={gltf.materials.grey} />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Mesh_Group_36_1.geometry}
      material={gltf.materials['grey-dark']}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
