<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 Cover.glb --transform --shadows --root=factory/
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('factory/Cover-transformed.glb', { useDraco: true })

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh castShadow receiveShadow geometry={gltf.nodes.Mesh_cover.geometry} material={gltf.materials['grey-dark']} />
    <T.Mesh castShadow receiveShadow geometry={gltf.nodes.Mesh_cover_1.geometry} material={gltf.materials.dark} />
    <T.Mesh castShadow receiveShadow geometry={gltf.nodes.Mesh_cover_2.geometry} material={gltf.materials.grey} />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
