<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 Forklift.glb --transform --shadows --root=factory/
Author: Andreas Heimowski (https://sketchfab.com/Gurkenbier)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-forklift-fbfb59ffcdf64a708f4caef9c6d1afba
Title: Low Poly Forklift
-->

<script>
	import { Group } from 'three';
	import { T, forwardEventHandlers } from '@threlte/core';
	import { useGltf } from '@threlte/extras';
	import { AutoColliders, Collider, RigidBody } from '@threlte/rapier';

	export const ref = new Group();

	const gltf = useGltf('factory/Forklift-transformed.glb', { useDraco: true });

	const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group position={[0, 1, 0]}>
			<Collider shape="cuboid" args={[0.75, 0.75, 0.5]} />
			<T.Mesh
				castShadow
				scale={0.25}
				position={[0, -0.75, 0]}
				geometry={gltf.nodes.Object_4.geometry}
				material={gltf.materials.LP_Material}
			/>
		</T.Group>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
