<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 StructureTall.glb --transform --shadows --root=factory/
-->

<script lang="ts">
	import { Group, MeshBasicMaterial, MeshStandardMaterial } from 'three';
	import { T, forwardEventHandlers } from '@threlte/core';
	import { useGltf } from '@threlte/extras';

	export const ref = new Group();

	const gltf = useGltf('factory/StructureTall-transformed.glb', { useDraco: true });

	const component = forwardEventHandlers();

	// let material = new MeshStandardMaterial({ color: '#00ffff' });
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Mesh
			castShadow
			receiveShadow
			geometry={gltf.nodes['Mesh_structure-tall'].geometry}
			material={gltf.materials.grey}
		/>
		<T.Mesh
			castShadow
			receiveShadow
			geometry={gltf.nodes['Mesh_structure-tall_1'].geometry}
			material={gltf.materials.dark}
		/>
		<T.Mesh
			castShadow
			receiveShadow
			geometry={gltf.nodes['Mesh_structure-tall_2'].geometry}
			material={gltf.materials['grey-dark']}
		/>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
