<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 Forklift.glb --transform --shadows --root=factory/
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('factory/Forklift-transformed.glb', { useDraco: true })

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh castShadow receiveShadow geometry={gltf.nodes.Supports.geometry} material={gltf.materials.LP_Material} />
    <T.Mesh castShadow receiveShadow geometry={gltf.nodes.Forks.geometry} material={gltf.materials.LP_Material} />
    <T.Mesh castShadow receiveShadow geometry={gltf.nodes.FrontWheels.geometry} material={gltf.materials.LP_Material} />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.BackLeftWheel.geometry}
      material={gltf.materials.LP_Material}
      position={[-1.99, 0.68, -1.28]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.BackRightWheel.geometry}
      material={gltf.materials.LP_Material}
      position={[-1.99, 0.68, 1.28]}
    />
    <T.Mesh castShadow receiveShadow geometry={gltf.nodes.Lights.geometry} material={gltf.materials.LP_Material} />
    <T.Mesh castShadow receiveShadow geometry={gltf.nodes.Roof.geometry} material={gltf.materials.LP_Material} />
    <T.Mesh castShadow receiveShadow geometry={gltf.nodes.Axels.geometry} material={gltf.materials.LP_Material} />
    <T.Mesh castShadow receiveShadow geometry={gltf.nodes.Body.geometry} material={gltf.materials.LP_Material} />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
